### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by meyergru** [Asn1Net/Asn1Net.Reader#2]
First of all: Nice package!

Here on Github, this package has 2 licenses:

1. Apache license
2. MIT license for a limited set of files

All C# files have an Apache license header - which is fine for me as this allows commercial use.

However, when you include the package via Nuget, there is a license.txt stating that the whole package is under AGPL, which poses some problems when the library is used for a server-side application like the one I have in mind.

Why is the Nuget license different? I would favor if this was brought into line, e.g. by removing or replacing license.txt with an Apache license in the Nuget package.

**Comment by peponeska** [comment]
I made the license change in 888a901beefb7d77b2a5deda6690dcef41bb3ecb. But I haven't made any nuget since then.

I'll try to make some time to do this in next few days.

**Comment by meyergru** [comment]
But the Nuget version is identical to Github with regard to the source code and version (1.1.0.1, that is).

**Comment by peponeska** [comment]
I usually change assembly version (and nuget version) just before making a release. That's why it has the same version. 

I haven't developed this project for quite a while and since then I've started a new one [ASN1Net](https://github.com/Asn1Net/Asn1Net) which combines BER Reader and DER Writer into one library. I also wanted to try different approach to parse ASN1 (substreams instead of placing parsed objects on stack). Sadly I'm not satisfied with the (Reader part of) ASN1Net project either and I haven't had time to finish it.

**Comment by meyergru** [comment]
I guess when you need to have an ASN.1 writer, you should support DER as well, for ASN1Net.Reader there should be no difference since anything that is being read could be DER or BER but given BER being the more general format, it can read either type.

I found it quite hard to dissect certain kind of certificates (or to be more specific: extended attributes), especially the content of qcStatements from EIDAS certificates. When I tried that using Java, I stumbled over BouncyCastle. However this library being very feature-rich, it is also badly documented and hard to employ correctly, so I looked for something simpler when we switched to C#.

Given an ETSI specification and ASN1Net.Reader, it was much easier to get at the neccessary information than with BouncyCastle, so for my application, it will suffice. I admire the simplicity of ASN1Net.Reader for this purpose, as my application is also security-related: The easier it is to understand, the less likely there is a hidden flaw.

**Comment by peponeska** [comment]
I'm glad that this library was helpful to you. I'm working with BouncyCastle quite often and it is like `guess your method` kind of library 😄 So that was the reason why I've implemented my own ASN.1 reader/writer library.

[New nuget](https://www.nuget.org/packages/Asn1Net.Reader/1.2.0) should be online any time now so this issue should be resolved. I'm closing the issue for now.
